// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJPRf0plXYzvjO0zon0_mqd1mHen4tq-M',
    appId: '1:739171047443:web:ed650016473a33d7eb47e6',
    messagingSenderId: '739171047443',
    projectId: 'ps154-a4a41',
    authDomain: 'ps154-a4a41.firebaseapp.com',
    storageBucket: 'ps154-a4a41.firebasestorage.app',
    measurementId: 'G-HM69DLKDNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC90JLUuAWJerAC0Do84KM_2oSaz5YAXrw',
    appId: '1:739171047443:android:9700581331b59ad4eb47e6',
    messagingSenderId: '739171047443',
    projectId: 'ps154-a4a41',
    storageBucket: 'ps154-a4a41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWhH7fP9D6h2392a1-mWInebiT7Qi9MuU',
    appId: '1:739171047443:ios:a2f03b339048c9bfeb47e6',
    messagingSenderId: '739171047443',
    projectId: 'ps154-a4a41',
    storageBucket: 'ps154-a4a41.firebasestorage.app',
    iosBundleId: 'com.example.pcrPoaBeneficiaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWhH7fP9D6h2392a1-mWInebiT7Qi9MuU',
    appId: '1:739171047443:ios:a2f03b339048c9bfeb47e6',
    messagingSenderId: '739171047443',
    projectId: 'ps154-a4a41',
    storageBucket: 'ps154-a4a41.firebasestorage.app',
    iosBundleId: 'com.example.pcrPoaBeneficiaryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJPRf0plXYzvjO0zon0_mqd1mHen4tq-M',
    appId: '1:739171047443:web:1722f2db78ec8910eb47e6',
    messagingSenderId: '739171047443',
    projectId: 'ps154-a4a41',
    authDomain: 'ps154-a4a41.firebaseapp.com',
    storageBucket: 'ps154-a4a41.firebasestorage.app',
    measurementId: 'G-326YMHB5FZ',
  );

}